### ISSUE TITLE
Download stats

### ISSUE THREAD

**Issue by Kimcmetzler** [quiltdata/quilt#1312] opened 2019-10-22 23:47 UTC
Is there a way to export the download metrics for 365 days, and view the total?

**Comment by akarve** [comment] 2019-10-23 00:11
We're in the process of updating the chart to show totals. I will add a backlog task for data downloads.

**Comment by Kimcmetzler** [comment] 2019-10-23 15:35
Thanks Aneesh! What about the capability to export/download those metrics?

**Comment by Kimcmetzler** [comment] 2019-10-24 22:24
Also, is there a way to see the download stats for each package rather than have them accumulated?

**Comment by akarve** [comment] 2019-10-25 01:10
Yes to all of the above :) they are all in our ticketing system. We'll start to unveil these features in the coming 30 days. To summarize:
* Update download counts
* Ability to download metrics
* Per-package metrics

**Comment by Kimcmetzler** [comment] 2019-10-25 15:37
Thank you Aneesh - you guys rock!

**Comment by JacksonMaxfield** [comment] 2019-11-08 22:44
@Kimcmetzler I was just told by @akarve that this is released!

https://open.quiltdata.com/b/allencell

I would say drop feedback about the new download options here?

**Comment by JacksonMaxfield** [comment] 2019-12-03 00:07
There is a bug:

![image](https://user-images.githubusercontent.com/17132317/70005224-a84bdb80-151d-11ea-985f-2ceca65455e9.png)

The grey transparent background on hover is always the same size when it should be resizing based off suffix length.

Also, any chance of removing "render operations" from download stats? Or maybe have a checkbox that is "with renders" vs "without renders"

**Comment by nl0** [comment] 2019-12-03 12:48
@JacksonMaxfield the display issue should be fixed by #1429. as for "render operations" -- AFAICT this is caused by a recent change related to extracting more than 1 level of extensions -- you should probably discuss this w/ @akarve

**Comment by akarve** [comment] 2020-03-13 01:58
Issue is now resolved and working

**Closed by akarve** 2020-03-13 01:58 UTC
